language: php

sudo: false
dist: trusty

git:
  depth: 3

notifications:
  email: false
  slack:
    secure: nk4GubRb9m0PQx7tT8OCkb4PTZPWxipKuezc/VLAT/h0cYMMSQoCSXZdQ1ojkFRgvrGABUfD9rS5Ro8sc11V6q6WrOogotcW7YrfpNoDxsOCLi+48XGSC41fDqUae9x09eHrS10tGK1IxvJBNU17g3Ic5Vx3zKSkLZNMK6ogpxfxPYTNTH53fxjJss58n1c5SOLDtHB0IMdrtYrGeTnd5uF9t6W4mRAV6km2KMRD1JbKfwivh3LsbHT+iCHDXOtcETz7xGYYl0xPBIh/n7nROq9NPg/j4CZLPazztBNcwwWRv1RzRRJIoPnG8IJQiPd4WKxeoaZbr/8NqWWHFYspAyndj1UhoxHE2vn6k9so0gkgrt5SwX8WKeQEyd12knLDMM0xAgKA9wKbTwkY6mvaM6CEW4P1WfwhqonvfKIBIOJWNkqs8TIr8RJFZlZYkBZak7ASOQ4MePiD8Kov/1ebKYx5AeRUWjHxC95hVZ02gnWIYjpDvDRINTxmRugnv4g4BIojBg8ZQg25cuhEtV6wEjDZmYbzjKM+6uwEYC2sWDajfDf6uBkZpfUrqk5no70tOnCb/hgLaIx47MxpuTJv3Gq4fUkvrNiAJx08Vr2GkcBhHaCVUUO3ofVUpLmu3XB5fQ5hIHSSj1MhE1Aj00XeNxk7smE0YQvkTlBBfQdA9qs=

branches:
  only:
    - master
    - "/^v[0-9\\.]+/"

cache:
  directories:
    - "${HOME}/.composer/cache"
    - "${TRAVIS_BUILD_DIR}/.plugin"

stages:
  - name: check
    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: test
    if: branch = master and tag IS blank and type IN (pull_request, api, cron)

before_script:
  - git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci
  - bash travis-ci/bin/prepare.sh install

jobs:
  fast_finish: true
  include:
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpcs.sh
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpmd.sh


    - stage: test
      language: php
      php: '7.3'
      env:
        - WP_VERSION=latest
        - COVERAGE_REPORT=1
        - ACTIVATE_POPULAR_PLUGINS=1
        - IGNORE_GUTENBERG_VERSION=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.3'
      env:
        - WP_VERSION=latest
        - WP_MULTISITE=1
        - COVERAGE_REPORT=1
        - ACTIVATE_POPULAR_PLUGINS=1
        - IGNORE_GUTENBERG_VERSION=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env:
        - WP_VERSION=5.0
        - WP_MULTISITE=1
        - COVERAGE_REPORT=1
        - ACTIVATE_POPULAR_PLUGINS=1
        - IGNORE_GUTENBERG_VERSION=1
      script: bash travis-ci/bin/php/wp-test.sh
