on:
  schedule:
    - cron: 0 15 * * 5
  repository_dispatch:
    types: [sync-workflows]
  workflow_dispatch:

name: Sync workflows
jobs:
  release:
    name: Sync workflows
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Sync workflows
        uses: technote-space/create-pr-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXECUTE_COMMANDS: |
            rm -rdf .github/workflows/.tmp
            mkdir -p .github/workflows/.tmp
            git clone --depth=1 https://github.com/technote-space/github-actions-workflows.git .github/workflows/.tmp/workflows

            bash .github/workflows/.tmp/workflows/wp-plugin/copy.sh

            sed -i "s/php: \[.\+$/php: ['7.3', '5.6']/" .github/workflows/ci.yml
            sed -i "s/WP_VERSION: \[.\+$/WP_VERSION: ['latest', '5.3']/" .github/workflows/ci.yml
            sed -i "s/ACTIVATE_POPULAR_PLUGINS/SEND_CODECOV/g" .github/workflows/ci.yml
            sed -i '/SEND_CODECOV: \$/d' .github/workflows/ci.yml
            sed -i '/TRAVIS_BUILD_DIR:/a \  ACTIVATE_POPULAR_PLUGINS: 1\n  IGNORE_GUTENBERG_VERSION: 1' .github/workflows/ci.yml
            sed -i 's/cron:.\+$/cron: 0 1 * * 0,4/' .github/workflows/update-dependencies.yml

            rm -rdf .github/workflows/.tmp
          COMMIT_MESSAGE: 'chore: sync workflows'
          PR_BRANCH_PREFIX: chore/
          PR_BRANCH_NAME: 'chore-sync-workflows'
          PR_TITLE: 'chore: sync workflows'
          ONLY_DEFAULT_BRANCH: true
